server {
    listen 80;

    location / {
        proxy_pass http://web:8080;
        proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
        proxy_set_header X-Real-IP \;
    }
}
